### PR TITLE
Update tests for WC 2.7

### PR DESCRIPTION
**Pull request by claudiulodro**
I've modified the tests to pass on WooCommerce 2.7. This primarily involved changing the selectors to work, as the basic functionality that was being tested still exists. Elements just have different selectors and slightly different text in some cases.

### CODE REVIEW

**Comment by gedex** [comment]
Rebased with `master`.

**Comment by gedex** [comment]
2 passes, 3 failing when testing checkout page:

```
npm run test:single test/checkout-page.js
```

Output:

```
  Checkout Page
    1) should displays cart items in order review
    2) allows customer to choose available payment methods
    ✓ allows customer to fill billing details (8847ms)
    ✓ allows customer to fill shipping details (3629ms)
    3) allows guest customer to place order


  2 passing (39s)
  3 failing

  1) Checkout Page should displays cart items in order review:
     NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//tr[contains(@class, "shipping") and .//td[contains(., "3.00")]]"}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
      at WebDriverError (node_modules/selenium-webdriver/lib/error.js:27:5)
      at NoSuchElementError (node_modules/selenium-webdriver/lib/error.js:242:5)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:639:15)
      at parseHttpResponse (node_modules/selenium-webdriver/http/index.js:538:13)
      at client_.send.then.response (node_modules/selenium-webdriver/http/index.js:472:11)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: WebDriver.findElement(By(xpath, //tr[contains(@class, "shipping") and .//td[contains(., "3.00")]]))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:377:17)
      at Driver.findElement (node_modules/selenium-webdriver/lib/webdriver.js:864:17)
      at Object.mouseMoveTo (node_modules/wp-e2e-webdriver/lib/helper.js:177:43)
      at ComponentCheckoutOrderReview._mouseMoveTo (src/components/component-checkout.js:13:17)
      at ComponentCheckoutOrderReview.hasShipping (src/components/component-checkout-order-review.js:45:8)
      at Context.<anonymous> (test/checkout-page.js:53:37)
      at node_modules/selenium-webdriver/testing/index.js:144:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1082:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:129:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
  From: Task: Checkout Page should displays cart items in order review
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)

  2) Checkout Page allows customer to choose available payment methods:
     NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//li[contains(@class, "wc_payment_method")]//label[contains(.,"Direct bank transfer")]"}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
      at WebDriverError (node_modules/selenium-webdriver/lib/error.js:27:5)
      at NoSuchElementError (node_modules/selenium-webdriver/lib/error.js:242:5)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:639:15)
      at parseHttpResponse (node_modules/selenium-webdriver/http/index.js:538:13)
      at client_.send.then.response (node_modules/selenium-webdriver/http/index.js:472:11)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: WebDriver.findElement(By(xpath, //li[contains(@class, "wc_payment_method")]//label[contains(.,"Direct bank transfer")]))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:377:17)
      at Driver.findElement (node_modules/selenium-webdriver/lib/webdriver.js:864:17)
      at CheckoutPage.selectPaymentMethod (src/pages/checkout-page.js:50:27)
      at Context.<anonymous> (test/checkout-page.js:72:38)
      at node_modules/selenium-webdriver/testing/index.js:144:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1082:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:129:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
  From: Task: Checkout Page allows customer to choose available payment methods
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)

  3) Checkout Page allows guest customer to place order:
     NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//li[contains(@class, "wc_payment_method")]//label[contains(.,"Cash on delivery")]"}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
      at WebDriverError (node_modules/selenium-webdriver/lib/error.js:27:5)
      at NoSuchElementError (node_modules/selenium-webdriver/lib/error.js:242:5)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:639:15)
      at parseHttpResponse (node_modules/selenium-webdriver/http/index.js:538:13)
      at client_.send.then.response (node_modules/selenium-webdriver/http/index.js:472:11)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: WebDriver.findElement(By(xpath, //li[contains(@class, "wc_payment_method")]//label[contains(.,"Cash on delivery")]))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:377:17)
      at Driver.findElement (node_modules/selenium-webdriver/lib/webdriver.js:864:17)
      at CheckoutPage.selectPaymentMethod (src/pages/checkout-page.js:50:27)
      at Context.<anonymous> (test/checkout-page.js:151:16)
      at node_modules/selenium-webdriver/testing/index.js:144:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1082:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:129:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
  From: Task: Checkout Page allows guest customer to place order
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)
```

**Comment by gedex** [comment]
Error above is fixed in https://github.com/woocommerce/wc-e2e-page-objects/pull/8/commits/b086b974b16e8ccf2a564c43218d1d8a816869f8.

**Comment by gedex** [comment]
Another error in checkout page:

```
 2) Checkout Page allows guest customer to place order:
     NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//li[contains(@class, "wc_payment_method")]//label[contains(.,"Cash on delivery")]"}
```

I see you updated payment method text in this PR. I updated the text back to camel case in checkout page test.

@claudiulodro can you fetch and retry testing checkout page?

```
npm run test:single test/checkout-page.js
```

It could be your test site settings differ with me.

**Comment by claudiulodro** [comment]
I tested with the master branch of WooCommerce. I get problems with the labels on the payment gateways, but everything else works great. 

```  2) Checkout Page allows guest customer to place order:
     NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//li[contains(@class, "wc_payment_method")]//label[contains(.,"Cash on Delivery")]"}
```
The lowercase version is the default title for the field, but it is customizable: https://github.com/woocommerce/woocommerce/blob/f9f6ac175b349f2b22e73438da7d8e73d49b1426/includes/gateways/cod/class-wc-gateway-cod.php#L78 

I would prefer to use the default values, so the tests pass on a fresh install of WooCommerce without having to change the settings. Thoughts?

**Comment by gedex** [comment]
> The lowercase version is the default title for the field, but it is customizable: 

Ok, will try with fresh install.

**Comment by gedex** [comment]
LGTM now. Thanks for the catch @claudiulodro !

**Pull request merged**
