### PR TITLE
Fix all the remaining tests

### PR DESCRIPTION
**Pull request by alisterscott**
Fix all the tests so we have 💯% pass rate in TravisCI

### CODE REVIEW

**Comment by alisterscott** [comment]
Yay 🎉

**Comment by alisterscott** [comment]
@gedex would you mind checking this? I'll merge and release a minor version bump and keep things 🍏

**Review by gedex — APPROVED** [review]
This looks really good now! :1st_place_medal: 

Thanks!

**Comment by rodrigoprimo** [comment]
That is awesome. Thanks for your work @alisterscott!

**Pull request merged**
